channels:
  - conda-forge
dependencies:
  # Jupyter
  - jupyterlab=2
  - nodejs=12
  - nbconvert=5.5
  - widgetsnbextension=3.5
  # Python Kernel
  - ipykernel=5.1
  - ipywidgets=7.5
  - ipyleaflet=0.12
  - altair=3.1
  - bqplot=0.12
  - dask=2.1
  - matplotlib=3.1
  - pandas=1.0
  - python=3.7
  - scikit-image=0.15
  - scikit-learn=0.21
  - seaborn=0.9
  - tensorflow=1.13
  - sympy=1.6
  - pyyaml
  - traittypes==0.2.1
  # update outdated repo2docker version
  - pip
  - pip:
      - jupyter-offlinenotebook>=0.1.0
      - jupyterlab_latex>=2.0.0
